/**
 * Downloads the brand fonts into `public/fonts/` and writes `src/styles/_fonts.scss`.
 *
 * The site used to pull these from fonts.googleapis.com at runtime, which costs a
 * third-party DNS lookup and connection before any text can paint, and leaks a
 * request per visitor. Self-hosting removes both.
 *
 * The Latin faces keep only the `latin` and `latin-ext` subsets, and the Arabic
 * companions keep only `arabic` — nothing ever renders Latin in Amiri or Tajawal,
 * and the Cyrillic and Vietnamese cuts Google serves are dead weight either way.
 *
 * Run with `node scripts/fetch-fonts.mjs`. It is a one-off; the woff2 files are
 * committed.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = join(root, "public", "fonts");

// Google only serves woff2 to a browser that says it can take it.
const USER_AGENT =
	"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const LATIN_SUBSETS = new Set(["latin", "latin-ext"]);
const ARABIC_SUBSETS = new Set(["arabic"]);

/**
 * `slug` becomes the filename stem, so keep it stable — the SCSS references it.
 *
 * Amiri and Tajawal are the Arabic halves of the type stack, appended to the
 * matching stacks in `shared/design-tokens/tokens.json`. A browser resolves a
 * stack per glyph, so an Arabic run finds them while Latin stays on Playfair and
 * Inter. Neither is variable: Amiri ships 400 and 700, and Tajawal has no 600, so
 * a semibold Arabic run matches 700.
 */
const FAMILIES = [
	{ query: "Playfair+Display:ital,wght@0,400..900", slug: "playfair-display", subsets: LATIN_SUBSETS },
	{ query: "Playfair+Display+SC:wght@400;700;900", slug: "playfair-display-sc", subsets: LATIN_SUBSETS },
	{ query: "Playfair:wght@400..700", slug: "playfair", subsets: LATIN_SUBSETS },
	{ query: "Inter:wght@400..600", slug: "inter", subsets: LATIN_SUBSETS },
	{ query: "Amiri:wght@400;700", slug: "amiri", subsets: ARABIC_SUBSETS },
	{ query: "Tajawal:wght@400;500;700", slug: "tajawal", subsets: ARABIC_SUBSETS },
];

async function fetchCss(query) {
	const url = `https://fonts.googleapis.com/css2?family=${query}&display=swap`;
	const response = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!response.ok) throw new Error(`${url} -> ${response.status}`);
	return response.text();
}

/** Splits the Google stylesheet into one record per `@font-face`, keeping its subset comment. */
function parseFaces(css) {
	const faces = [];
	const pattern = /\/\*\s*([\w-\[\]]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;

	for (const [, subset, body] of css.matchAll(pattern)) {
		const read = (property) => new RegExp(`${property}:\\s*([^;]+);`).exec(body)?.[1]?.trim();
		const url = /url\((https:[^)]+)\)/.exec(body)?.[1];
		if (!url) continue;

		faces.push({
			subset,
			url,
			style: read("font-style") ?? "normal",
			weight: read("font-weight") ?? "400",
			unicodeRange: read("unicode-range"),
		});
	}

	return faces;
}

mkdirSync(fontDir, { recursive: true });

const rules = [];
let downloaded = 0;

for (const family of FAMILIES) {
	const css = await fetchCss(family.query);
	const faces = parseFaces(css).filter((face) => family.subsets.has(face.subset));

	if (!faces.length) {
		throw new Error(`no ${[...family.subsets].join("/")} faces returned for ${family.query}`);
	}

	for (const face of faces) {
		const isVariable = face.weight.includes(" ");
		const weightSlug = isVariable ? "variable" : face.weight;
		const file = `${family.slug}-${weightSlug}-${face.subset}.woff2`;

		const response = await fetch(face.url, { headers: { "User-Agent": USER_AGENT } });
		const buffer = Buffer.from(await response.arrayBuffer());
		writeFileSync(join(fontDir, file), buffer);
		downloaded += 1;

		const displayName = decodeURIComponent(family.query.split(":")[0]).replaceAll("+", " ");

		rules.push(
			[
				"@font-face {",
				`\tfont-family: "${displayName}";`,
				`\tfont-style: ${face.style};`,
				`\tfont-weight: ${face.weight};`,
				"\tfont-display: swap;",
				`\tsrc: url("/fonts/${file}") format("woff2");`,
				face.unicodeRange ? `\tunicode-range: ${face.unicodeRange};` : null,
				"}",
			]
				.filter(Boolean)
				.join("\n"),
		);

		console.log(`${file}  ${Math.round(buffer.length / 1024)}kB`);
	}
}

const header = `// GENERATED BY web/scripts/fetch-fonts.mjs - DO NOT EDIT BY HAND.
//
// The brand faces are served from public/fonts/ rather than fonts.googleapis.com,
// so first paint does not wait on a third-party connection. Re-run the script to
// change weights or add a subset.
`;

writeFileSync(join(root, "src", "styles", "_fonts.scss"), `${header}\n${rules.join("\n\n")}\n`, "utf8");

console.log(`\n${downloaded} files, ${rules.length} @font-face rules`);
